### PR TITLE
Account for overlap

### LINKED ISSUE #5: Add an option to union enclosed fragments
Given a scenario like the below screenshot, it would be awesome if we had an option that would do a second pass to unify regions with junction points at both terminals.

For example, looking at selection 125, simply use it to union together all adjoining selections. This would create two ROIs:

* 105 + 125 + 107
* 120 + 125 + 126

screenshot from 2015-11-04 10 54 53

### PR DESCRIPTION
**Pull request by hinerm**
Adds a choice for overlap resolution and a slope (straightness) based method for resolving overlap.

Closes #5

### CODE REVIEW

**Comment by hinerm** [comment]
@thorstenwagner I updated this PR to fix the merge conflicts.

**Comment by thorstenwagner** [comment]
@hinerm Thank you so much! I will merge it this evening or tomorrow morning.  My mother came to visit me ;-)

**Comment by hinerm** [comment]
:+1:  awesome! :smile: have fun!

**Comment by thorstenwagner** [comment]
@hinerm I've now merged the pull request. However, for my example it seems not to do anything:
ridge_test

I've used the following settings:
Line Width: 6
High contrast: 255
Low contrast: 250
Checked: Add to manager, display results, show ids, show junctions points and extend line
Method for overlap resolution: Slope

What I'm doing wrong?

**Comment by imagejan** [comment]
@thorstenwagner Your png image has a strange LUT and scaling. I had to switch the LUT to "Grays" and scale the 0-1 intensity range to 0-255 so that your parameters worked me. In addition, I used a small Gaussian blur to avoid a bunch of small line artifacts at the line ends.

With these adjustments, I get the following result:

8882e5ac-8861-11e5-9367-0a943108ad76-3

The way the lines were joined is not how I'd expect it, however...
@hinerm Any comments?

**Comment by thorstenwagner** [comment]
Maybe the slope it calculated to locally?

**Comment by hinerm** [comment]
@thorstenwagner @imagejan - I downloaded the original, converted to a `tif` and tried.

With no parameter adjustment I got an "incorrect" segmentation like @imagejan 
Setting the sigma to 3 in the ridge detection UI (and no other changes) gave me "expected" segmentation.

>Maybe the slope it calculated too locally?

I think this definitely could be a problem.  Right now the [distance is hard-coded](https://github.com/thorstenwagner/ij-ridgedetection/blob/master/src/main/java/de/biomedical_imaging/ij/steger/SlopeOverlapResolver.java#L45).

I originally thought that making a configuration option would be useful. But now I'm thinking it might be better for each fragment to do some searching and use the longest section that it can (e.g. check straightness 5 positions back from intersection.. then 10, then 15, etc.. and use the longest section possible without significant change in straightness/slope).

I'm definitely open to suggestions!

**Comment by hinerm** [comment]
screenshot from 2015-11-11 09 12 02
screenshot from 2015-11-11 09 12 21

**Comment by hinerm** [comment]
@thorstenwagner 
>I've used the following settings:
>Line Width: 6
>High contrast: 255
>Low contrast: 250
>Checked: Add to manager, display results, show ids, show junctions points and extend line
>Method for overlap resolution: Slope
>
>What I'm doing wrong?

This particular case was a bug I [believe I have fixed now](https://github.com/hinerm/ij-ridgedetection/commit/42286245d8db0f509937dd2c87c0f2b71a659325).

**Comment by thorstenwagner** [comment]
@hinerm 
Perfect, I guess it works good enough to make it available as release! Thank you so much for contributing! It is now available via update size as well.

Would you be so kind to update the fiji wiki page and descripe what the slope resolver exactly does?
http://fiji.sc/Ridge_Detection

>I think this definitely could be a problem. Right now the distance is hard-coded.
>
>I originally thought that making a configuration option would be useful. But now I'm thinking it might >be better for each fragment to do some searching and use the longest section that it can (e.g. >check straightness 5 positions back from intersection.. then 10, then 15, etc.. and use the longest >section possible without significant change in straightness/slope).
>
>I'm definitely open to suggestions!

I would try to use a distance relative to the line length but not smaller as your hard corded distance.

**Comment by thorstenwagner** [comment]
@hinerm Another suggestion: What about updating the junctions points, when you merge two lines?
For my example, the two junction points could be merged to one junction point, because no other line is using small crossing line. Do you know what I mean?

>Line Width: 6
>High contrast: 255
>Low contrast: 250
>Checked: Add to manager, display results, show ids, show junctions points and extend line
>Method for overlap resolution: Slope

**Comment by hinerm** [comment]
>It is now available via update size as well.

ack, I have a couple bug fixes that [need to be merged](https://github.com/thorstenwagner/ij-ridgedetection/pull/14)!

>Would you be so kind to update the fiji wiki page and descripe what the slope resolver exactly does?

Happily!! :smile: 

>I would try to use a distance relative to the line length but not smaller as your hard corded distance.

I updated it to [recursively search](https://github.com/hinerm/ij-ridgedetection/commit/60c1fdc325bb062f6b4129622b8e400dae5b59e9) for the longest, straight section it can find.. I hope that will be more robust.

**Comment by hinerm** [comment]
>What about updating the junctions points, when you merge two lines?

You're right.. I need to do that..

**Comment by thorstenwagner** [comment]
> ack, I have a couple bug fixes that need to be merged!

Argh! Ok, I will merge it and release again... :Smile:

**Comment by hinerm** [comment]
yay! thank you! I will work on the wiki page

**Pull request merged**
